### ISSUE TITLE
Cannot create container for service mysql-otf

### ISSUE THREAD

**Issue by mgodlewski** [emilieguth/otf-docker#3]
Hello,

on docker-compose up, I've got this error message :

`ERROR: for mysql-otf  Cannot create container for service mysql-otf: invalid mount config for type "bind": bind source path does not exist: /home/xxx/otf-docker/docker/myql/tmp`

This is due to a typo (myql => mysql) in 
https://github.com/emilieguth/otf-docker/blob/efd5816f145e8c6c9f1236f3f4c6b4737c16fb25/docker-compose.yml#L11

Thank you for your work

**Comment by mgodlewski** [comment]
Already fixed in  #1

**Comment by emilieguth** [comment]
This if fixed in https://github.com/emilieguth/otf-docker/commit/66410cc6ef638e574e58ef7062cd5d55282163ca. Thanks for noticing.
